# Site Settings
title: TypeScript and Free Code Camp 
email: jgsimmerman@gmail.com
description: >
    Learning TypeScript by following the Free Code Camp path.  
baseurl: "/30days"
url: "http://ibws.com/30days"
twitter_username: jgsimmerman
github_username:  jgsimmerman
# Build Settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
kramdown:
  input: GFM

#Disqus post comments
disqus_shortname: jacobsimmerman
